apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: three-tier
  labels:
    role: frontend
    env: demo
spec: 
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec: 
      #imagePullSecrets: as i have public registry no need of secrets
      #- name: ecr-registry-secret
      containers:
      - name: frontend
        image: public.ecr.aws/v4v8i4t0/threetier-frontend:latest
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://app.18.223.235.75.nip.io/api/tasks"
        ports:
        - containerPort: 3000